name = "connorbrayapi"
main = "./src/index.ts"
routes = [{pattern = "api.connorbray.net/*", zone_id = "e8496c1028b3218d304c07b74fe48c8d"}]
compatibility_date = "2023-03-18"

[build]
command = "yarn"

[env.producton]
name = "connorbrayapi"

#[[services]]
#binding = "api"
#service = "connorbrayapi"
#environment = "production"